import 'package:flutter/material.dart';
import 'package:recipe/Recipes/recipedetails.dart';

class Recipe extends StatefulWidget {
  const Recipe({super.key});

  @override
  State<Recipe> createState() => _RecipeState();
}

class _RecipeState extends State<Recipe> {
  List<Map<String, dynamic>> recipes = [
    {
      'img': 'assets/lahori fish fry.jpg',
      'title': 'Lahori Fish Fry',
      'time': '45 min',
      'ingredients': [
        '500g Rohu fish fillets',
        '2 tbsp lemon juice',
        '1 tsp turmeric powder',
        '1 tbsp red chili powder',
        '1 tsp cumin powder',
        '1 tsp coriander powder',
        '1 tsp garam masala',
        'Salt to taste',
        '4 tbsp gram flour (besan)',
        'Oil for frying',
      ],
      'steps': [
        'Wash the fish fillets and marinate with lemon juice, salt, turmeric, red chili powder, cumin powder, coriander powder, and garam masala. Let it rest for 30 minutes.',
        'Coat each marinated fish fillet evenly with gram flour.',
        'Heat oil in a frying pan over medium heat.',
        'Fry the fish fillets until golden brown and crispy on both sides.',
        'Remove and drain on paper towels.',
        'Serve hot with mint chutney or lemon wedges.',
      ],
    },
    {
      'img': 'assets/aloo gobhi.jpg',
      'title': 'Aloo Gobhi',
      'time': '40 min',
      'ingredients': [
        '2 cups cauliflower florets',
        '2 medium potatoes, peeled and cubed',
        '1 onion, finely chopped',
        '2 tomatoes, chopped',
        '2 green chilies, chopped',
        '1 tsp cumin seeds',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp coriander powder',
        'Salt to taste',
        '3 tbsp oil',
        'Fresh coriander leaves for garnish',
      ],
      'steps': [
        'Heat oil in a pan and add cumin seeds.',
        'When they splutter, add onions and sauté until golden brown.',
        'Add chopped tomatoes and green chilies, cook until soft.',
        'Add turmeric, red chili, coriander powder, and salt.',
        'Add potatoes and cauliflower, mix well.',
        'Cover and cook on low heat for 20-25 minutes or until vegetables are tender.',
        'Garnish with fresh coriander leaves and serve hot.',
      ],
    },
    {
      'img': 'assets/chapli kabab.jpg',
      'title': 'Chapli Kabab',
      'time': '1 hr 30 min',
      'ingredients': [
        '500g minced beef or mutton',
        '1 medium onion, finely chopped',
        '2 tomatoes, finely chopped',
        '2 green chilies, finely chopped',
        '1 tbsp crushed pomegranate seeds (anardana)',
        '2 tbsp coriander seeds, roasted and crushed',
        '1 tsp cumin seeds, roasted and crushed',
        '1 tsp red chili flakes',
        '1 tsp garam masala',
        '1 tsp salt',
        '1 egg',
        '2 tbsp cornmeal or gram flour',
        'Fresh coriander leaves, chopped',
        'Oil for frying',
      ],
      'steps': [
        'In a large bowl, combine minced meat, onion, tomatoes, green chilies, pomegranate seeds, coriander seeds, cumin seeds, chili flakes, garam masala, salt, egg, cornmeal, and coriander leaves.',
        'Mix thoroughly until all ingredients are combined well.',
        'Shape the mixture into flat round patties.',
        'Heat oil in a frying pan over medium heat.',
        'Fry patties on both sides until fully cooked and crispy.',
        'Drain on paper towels and serve hot with naan or chutney.',
      ],
    },
    {
      'img': 'assets/karela.jpg',
      'title': 'Karela (Bitter Gourd) Fry',
      'time': '50 min',
      'ingredients': [
        '4 medium karela (bitter gourds), sliced thin',
        '1 tsp salt',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp coriander powder',
        '1 tsp cumin powder',
        '2 tbsp oil',
        '1 onion, sliced',
        '2 green chilies, chopped',
      ],
      'steps': [
        'Sprinkle salt on sliced karela and leave for 30 minutes. Then rinse to reduce bitterness.',
        'Heat oil in a pan, add onions and sauté until golden brown.',
        'Add green chilies and karela slices.',
        'Add turmeric, red chili, coriander, and cumin powders.',
        'Cook on medium heat stirring occasionally until karela is tender and cooked through.',
        'Serve hot as a side dish.',
      ],
    },
    {
      'img': 'assets/nihari.jpeg',
      'title': 'Nihari',
      'time': '4 hrs',
      'ingredients': [
        '1 kg beef shank or marrow bones',
        '3 tbsp cooking oil',
        '2 onions, sliced',
        '2 tbsp ginger-garlic paste',
        '1 tbsp red chili powder',
        '1 tbsp coriander powder',
        '1 tsp turmeric powder',
        '2 tsp garam masala',
        'Salt to taste',
        '4 cups water',
        'Fresh ginger, julienned (for garnish)',
        'Lemon wedges (for serving)',
        'Fresh coriander leaves (for garnish)',
      ],
      'steps': [
        'Heat oil in a large pot and sauté onions until golden brown.',
        'Add ginger-garlic paste and cook for 2 minutes.',
        'Add beef shanks and brown on all sides.',
        'Add red chili, coriander, turmeric powder, and salt.',
        'Pour water, bring to boil, then reduce heat and simmer for 3-4 hours until meat is tender and broth thickens.',
        'Add garam masala and cook for another 10 minutes.',
        'Serve hot garnished with ginger, coriander, and lemon wedges with naan or rice.',
      ],
    },
    {
      'img': 'assets/palak paneer.jpeg',
      'title': 'Palak Paneer',
      'time': '45 min',
      'ingredients': [
        '250g paneer, cubed',
        '500g spinach (palak), washed and chopped',
        '1 onion, finely chopped',
        '2 tomatoes, pureed',
        '1 tbsp ginger-garlic paste',
        '1 tsp cumin seeds',
        '1 tsp garam masala',
        '1 tsp red chili powder',
        'Salt to taste',
        '2 tbsp oil',
        'Fresh cream (optional)',
      ],
      'steps': [
        'Blanch spinach in boiling water for 2-3 minutes and puree it.',
        'Heat oil in a pan, add cumin seeds, then onions and sauté until golden brown.',
        'Add ginger-garlic paste and cook for 2 minutes.',
        'Add tomato puree, red chili powder, salt, and cook until oil separates.',
        'Add pureed spinach and cook for 5 minutes.',
        'Add paneer cubes and garam masala, simmer for 5 minutes.',
        'Garnish with fresh cream if desired and serve hot with roti or rice.',
      ],
    },
    {
      'img': 'assets/pizza with chicken fatija.jpg',
      'title': 'Chicken Fajita Pizza',
      'time': '1 hr',
      'ingredients': [
        '1 pizza base',
        '200g cooked chicken strips seasoned with fajita spices',
        '1 onion, sliced',
        '1 bell pepper, sliced',
        '1 cup mozzarella cheese, shredded',
        '1 tbsp olive oil',
        'Salt and pepper to taste',
        '1 tsp chili powder',
        '1 tsp cumin powder',
      ],
      'steps': [
        'Preheat oven to 220°C (430°F).',
        'Heat olive oil in a pan, sauté onions and bell peppers until tender.',
        'Add chicken strips, chili powder, cumin powder, salt, and pepper. Mix well.',
        'Place pizza base on baking tray, spread chicken and veggies evenly.',
        'Sprinkle mozzarella cheese on top.',
        'Bake for 12-15 minutes until cheese melts and crust is golden.',
        'Serve hot.',
      ],
    },
    {
      'img': 'assets/tea.jpg',
      'title': 'Doodh Patti Chai (Milk Tea)',
      'time': '15 min',
      'ingredients': [
        '2 cups water',
        '1 cup milk',
        '2 tbsp tea leaves (black tea)',
        '2-3 cardamom pods, crushed',
        'Sugar to taste',
      ],
      'steps': [
        'Boil water in a pot.',
        'Add tea leaves and cardamom pods, boil for 3-4 minutes.',
        'Add milk and sugar, bring to boil again.',
        'Simmer for 5 minutes on low heat.',
        'Strain and serve hot.',
      ],
    },
    {
      'img': 'assets/zarda.jpg',
      'title': 'Zarda (Sweet Rice)',
      'time': '1 hr',
      'ingredients': [
        '2 cups basmati rice',
        '1 ½ cups sugar',
        '4 cups water',
        '1 cup milk',
        '½ cup ghee',
        '1 tsp cardamom powder',
        'Chopped nuts (almonds, pistachios)',
        'Food color (optional, yellow or orange)',
        'Raisins',
      ],
      'steps': [
        'Wash and soak rice for 30 minutes.',
        'Boil water, add soaked rice, cook until 70% done, then drain.',
        'In a separate pot, heat ghee and add cooked rice.',
        'Add sugar, milk, cardamom powder, and food color if using.',
        'Cook on low heat, stirring gently until rice is fully cooked and syrup thickens.',
        'Add chopped nuts and raisins, mix gently.',
        'Serve warm.',
      ],
    },
    {
      'img': 'assets/daal tarka.jpg',
      'title': 'Daal Tadka',
      'time': '40 min',
      'ingredients': [
        '1 cup split red lentils (masoor daal)',
        '3 cups water',
        '1 onion, chopped',
        '2 tomatoes, chopped',
        '2 green chilies, chopped',
        '1 tsp cumin seeds',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp garam masala',
        'Salt to taste',
        '2 tbsp oil or ghee',
        'Fresh coriander for garnish',
      ],
      'steps': [
        'Wash daal and cook with water, turmeric, and salt until soft.',
        'In a separate pan, heat oil, add cumin seeds and let splutter.',
        'Add onions, sauté until golden brown.',
        'Add tomatoes and green chilies, cook until soft.',
        'Add red chili powder and garam masala.',
        'Mix the cooked daal into the pan and simmer for 5-10 minutes.',
        'Garnish with fresh coriander and serve hot.',
      ],
    },
    {
      'img': 'assets/eggcurry.jpeg',
      'title': 'Egg Curry',
      'time': '50 min',
      'ingredients': [
        '6 boiled eggs, peeled',
        '2 onions, finely chopped',
        '2 tomatoes, pureed',
        '2 green chilies, chopped',
        '1 tbsp ginger-garlic paste',
        '1 tsp turmeric powder',
        '1 tsp red chili powder',
        '1 tsp coriander powder',
        '1 tsp garam masala',
        'Salt to taste',
        '3 tbsp oil',
        'Fresh coriander leaves for garnish',
      ],
      'steps': [
        'Heat oil in a pan, sauté onions until golden brown.',
        'Add ginger-garlic paste and cook for 2 minutes.',
        'Add tomato puree, turmeric, red chili powder, coriander powder, and salt.',
        'Cook until oil separates from the masala.',
        'Add boiled eggs and simmer for 10 minutes.',
        'Sprinkle garam masala and garnish with coriander leaves.',
        'Serve hot with roti or rice.',
      ],
    },
    {
      'img': 'assets/shami kabab.jpg',
      'title': 'Shami Kabab',
      'time': '1 hr 30 min',
      'ingredients': [
        '500g minced beef or mutton',
        '1 cup soaked chana dal (split chickpeas)',
        '1 onion, chopped',
        '2 green chilies, chopped',
        '1 tbsp ginger-garlic paste',
        '1 tsp red chili powder',
        '1 tsp coriander powder',
        '1 tsp garam masala',
        'Salt to taste',
        '1 egg',
        '2 tbsp cornflour',
        'Oil for frying',
        'Fresh coriander leaves for garnish',
      ],
      'steps': [
        'Cook soaked chana dal until soft and mash it.',
        'Mix minced meat, mashed dal, onions, green chilies, ginger-garlic paste, and spices thoroughly.',
        'Add egg and cornflour to bind the mixture.',
        'Shape mixture into small flat patties.',
        'Heat oil and fry patties until golden and cooked through.',
        'Serve hot garnished with coriander leaves and chutney.',
      ],
    },
    {
      'img': 'assets/vegetablebeefstew.jpg',
      'title': 'Vegetable Beef Stew',
      'time': '2 hrs',
      'ingredients': [
        '500g beef chunks',
        '1 carrot, chopped',
        '1 potato, chopped',
        '1 onion, chopped',
        '2 tomatoes, chopped',
        '2 cloves garlic, minced',
        '1 tsp black pepper',
        '1 tsp salt',
        '2 tbsp oil',
        '2 cups water or beef broth',
        'Fresh coriander for garnish',
      ],
      'steps': [
        'Heat oil in a large pot, brown beef chunks.',
        'Add onions and garlic, sauté until soft.',
        'Add tomatoes, salt, and pepper.',
        'Pour water or broth, bring to boil.',
        'Add carrots and potatoes.',
        'Cover and simmer on low heat for 1.5-2 hours until beef is tender.',
        'Garnish with fresh coriander and serve hot.',
      ],
    },
    {
      'img': "assets/a2.jpg",
      'title': 'Biryani',
      'time': '1 hr 15 min',
      'subtitle': 'Aromatic rice and spiced meat',
      'ingredients': [
        '2 cups basmati rice',
        '500g chicken or mutton',
        '2 onions, thinly sliced',
        '2 tomatoes, chopped',
        '4 green chilies, slit',
        '1 cup yogurt',
        '2 tbsp ginger garlic paste',
        '1/2 tsp turmeric powder',
        '2 tsp red chili powder',
        '1 tbsp garam masala',
        '4 cups water',
        '1/4 cup cooking oil',
        'Salt to taste',
        'Fresh coriander and mint leaves',
        'Saffron soaked in warm milk (optional)',
      ],
      'steps': [
        'Wash and soak rice for 30 minutes.',
        'Heat oil, fry onions until golden brown and set aside half for garnishing.',
        'Add ginger garlic paste, tomatoes, and cook until oil separates.',
        'Add chicken/mutton, spices, yogurt, salt, and cook until meat is tender.',
        'Boil water, add soaked rice and cook until 70% done, drain water.',
        'Layer meat and rice in a pot, add fried onions, herbs, and saffron milk on top.',
        'Cover tightly and cook on low heat (dum) for 25-30 minutes.',
        'Serve hot with raita or salad.',
      ],
    },
    {
      'img': "assets/beefkorma.jpg",
      'title': 'Beef Korma',
      'time': '2 hrs',
      'subtitle': 'Rich, creamy and flavorful curry',
      'ingredients': [
        '1 kg beef, cut into cubes',
        '3 onions, thinly sliced',
        '1 cup yogurt',
        '2 tbsp ginger garlic paste',
        '1 tsp turmeric powder',
        '2 tsp red chili powder',
        '1 tbsp coriander powder',
        '1 tbsp garam masala',
        '1/2 cup cooking oil',
        '1 cup water',
        'Salt to taste',
        'Fresh coriander for garnish',
      ],
      'steps': [
        'Heat oil and fry onions until golden brown, remove half for garnish.',
        'Add ginger garlic paste and sauté for 2 minutes.',
        'Add beef and brown on all sides.',
        'Add spices and salt, mix well.',
        'Add yogurt and water, cover and cook on low heat until beef is tender (about 1.5-2 hours).',
        'Garnish with fried onions and fresh coriander before serving.',
      ],
    },
    {
      'img': "assets/chicken.jpeg",
      'title': 'Chicken',
      'time': '45 min',
      'subtitle': 'Juicy and tender grilled chicken',
      'ingredients': [
        '1 kg chicken pieces',
        '1 cup yogurt',
        '2 tbsp ginger garlic paste',
        '1 tsp red chili powder',
        '1 tsp turmeric powder',
        '1 tsp garam masala',
        '1 tbsp lemon juice',
        'Salt to taste',
        '2 tbsp cooking oil',
      ],
      'steps': [
        'Mix yogurt, spices, lemon juice, and ginger garlic paste to make marinade.',
        'Coat chicken pieces in marinade and refrigerate for at least 1 hour.',
        'Heat grill or pan with oil, cook chicken until fully done and browned on all sides.',
        'Serve hot with chutney or salad.',
      ],
    },
    {
      'img': "assets/creamy pasta salad.jpg",
      'title': 'Creamy Pasta Salad',
      'time': '25 min',
      'subtitle': 'Fresh veggies tossed with creamy dressing',
      'ingredients': [
        '2 cups cooked pasta (penne or rotini)',
        '1 cup chopped cucumber',
        '1 cup chopped tomatoes',
        '1/2 cup sweet corn',
        '1/2 cup diced bell peppers',
        '1/2 cup mayonnaise',
        '2 tbsp yogurt',
        '1 tbsp lemon juice',
        'Salt and pepper to taste',
        'Fresh parsley or coriander for garnish',
      ],
      'steps': [
        'Cook pasta according to package instructions, rinse and drain.',
        'In a large bowl, mix mayonnaise, yogurt, lemon juice, salt, and pepper to make dressing.',
        'Add pasta and chopped vegetables to the dressing and toss well.',
        'Garnish with fresh parsley or coriander and chill before serving.',
      ],
    },
    {
      'img': "assets/kheer.jpg",
      'title': 'Kheer',
      'time': '1 hr',
      'subtitle': 'Sweet rice pudding with cardamom',
      'ingredients': [
        '1/2 cup basmati rice',
        '1 liter full cream milk',
        '1 cup sugar',
        '4-5 green cardamoms, crushed',
        '1/4 cup chopped almonds and pistachios',
        '1 tbsp raisins (optional)',
      ],
      'steps': [
        'Wash rice and soak for 30 minutes.',
        'Boil milk in a heavy bottom pot.',
        'Add rice and cook on low heat, stirring frequently until rice is soft and milk thickens.',
        'Add sugar, cardamom, and cook for another 10 minutes.',
        'Garnish with nuts and raisins before serving chilled or warm.',
      ],
    },
    {
      'img': "assets/mutton cury.jpg",
      'title': 'Mutton Curry',
      'time': '2 hrs 30 min',
      'subtitle': 'Slow-cooked spicy and tender mutton',
      'ingredients': [
        '1 kg mutton pieces',
        '3 onions, thinly sliced',
        '2 tomatoes, chopped',
        '2 tbsp ginger garlic paste',
        '2 tsp red chili powder',
        '1 tsp turmeric powder',
        '1 tbsp coriander powder',
        '1 tbsp garam masala',
        '1/2 cup cooking oil',
        '1 cup water',
        'Salt to taste',
        'Fresh coriander for garnish',
      ],
      'steps': [
        'Heat oil and fry onions until golden brown; set some aside for garnish.',
        'Add ginger garlic paste and sauté for 2 minutes.',
        'Add mutton and cook until browned.',
        'Add tomatoes, spices, and salt; cook until oil separates.',
        'Add water, cover, and simmer on low heat for 2 hours or until mutton is tender.',
        'Garnish with fried onions and fresh coriander.',
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: recipes.length,
      itemBuilder: (context, index) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListTile(
            leading: CircleAvatar(
              radius: 40,
              backgroundImage: AssetImage(recipes[index]['img'] ?? ''),
            ),
            title: Text(
              recipes[index]['title'] ?? '',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.w500),
            ),
            trailing: InkWell(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => RecipeDetails(
                      img: recipes[index]['img'],
                      title: recipes[index]['title'],
                      ingredients: recipes[index]['ingredients'],
                      steps: recipes[index]['steps'],
                      time: recipes[index]['time'],
                    ),
                  ),
                );
              },
              child: Icon(Icons.arrow_forward_ios),
            ),
          ),
        );
      },
    );
  }
}
